# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Erastosthenes Sieve
#'
#' @description
#' \code{erastosthenesSieve} calculates the all prime numbers up till given
#' limit.
#' \url{https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes} for more
#' info about how it works.
#'
#' @section Maintainers:
#' Fazendaaa
#'
#' @author Fazendaaa
#'
#' @param limit Calculation limit
#'
#' @return A list containing all prime numbers
#'
#' @examples
#' erastosthenesSieve(100)
#' erastosthenesSieve(200)
#' erastosthenesSieve(300)
#'
#' @export
erastosthenesSieve <- function(limit) {
    .Call(`_sieveR_erastosthenesSieve`, limit)
}

